name: Test Automation Workflow

on:
  schedule :
  - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=true

    - name: Test Log Artifact
      uses: actions/upload-artifact@v5.0.0
      with:
        name: Test Logs
        path: logs/

    - name: Upload Test Reports
      uses: actions/upload-artifact@v5.0.0
      with:
        name: Reports
        path: report.html

    - name: Test Execution Status
      run: echo "Test Execution Completed"
    
